import type { ProposalData } from '../../lib/proposals/types';

export const mailingAuthorityBaseProposal: ProposalData = {
  id: 'base-mailing-8c42', mode: 'offer', client: 'Oferta base · Mailing', dateLabel: '2026', eyebrow: 'Mailing + producción audiovisual',
  titleLines: ['Sistema de mailing', 'y producción'], accentLine: 'audiovisual.',
  introduction: 'Configuramos campañas de email y producimos videos para que tu equipo pueda abrir conversaciones, dar seguimiento y llegar a reuniones con más contexto.',
  quote: 'Es una implementación para empresas que necesitan ordenar su prospección y contar mejor lo que hacen antes de pedir una reunión.', heroStats: [],
  heroSummary: { title: 'Qué incluye el servicio', items: [{ title: 'Configuración técnica', body: 'Dominios, correos y autenticación para enviar de forma ordenada.' }, { title: 'Campañas de email', body: 'Segmentación, secuencias, seguimiento y derivación de respuestas.' }, { title: 'Producción audiovisual', body: 'Videos breves que explican la oferta y acompañan la conversación comercial.' }] },
  sectionLabels: { diagnosis: 'Qué resolvemos', solution: 'Qué instalamos', content: 'Contenido para las campañas', investment: 'Inversión', timeline: 'Cómo empezamos', closing: '¿Te interesa?' },
  interestOptions: ['Quiero implementar el sistema completo', 'Quiero operar campañas de email cada mes', 'Quiero cotizar videos para mis campañas', 'Quiero conversar primero'],
  diagnosis: { title: 'Mailing y contenido para generar conversaciones comerciales.', introduction: 'El email abre un primer contacto. El video, la oferta y el seguimiento ayudan a que la persona entienda por qué vale la pena responder.', stats: [{ value: '01', label: 'Prospección ordenada', context: 'Contactamos cuentas definidas por tipo de empresa, cargo y problema.' }, { value: '02', label: 'Mensaje claro', context: 'Creamos emails y piezas audiovisuales que explican la oferta sin promesas vacías.' }, { value: '03', label: 'Seguimiento visible', context: 'Las respuestas se clasifican y se derivan a CRM o agenda.' }], conclusion: 'El sistema une infraestructura, mensajes y contenido para que el equipo comercial no dependa solo de contactos manuales.' },
  solution: { title: 'Construimos y operamos el sistema completo.', introduction: 'Primero dejamos lista la base técnica y comercial. Después lanzamos, medimos y ajustamos las campañas de forma mensual.', pillars: [{ title: 'Oferta y audiencia', description: 'Definimos a quién contactar, qué problema resolver y qué llamada a la acción usar.', tag: 'ICP · Mensaje' }, { title: 'Envío de emails', description: 'Configuramos dominios, correos, autenticación y secuencias para proteger la entregabilidad.', tag: 'SPF · DKIM · DMARC' }, { title: 'Seguimiento comercial', description: 'Clasificamos respuestas y las enviamos al CRM, WhatsApp o agenda según el caso.', tag: 'CRM · Agenda' }, { title: 'Videos para vender', description: 'Producimos VSL, clips o casos de uso para incluir en campañas y seguimiento.', tag: 'Producción · Edición' }] },
  content: { title: 'Videos que acompañan cada conversación.', introduction: 'Cada grabación se convierte en piezas para email, LinkedIn, landing pages y seguimiento comercial.', images: [{ src: '/gc-vsl-1.png', label: 'Video experto', caption: 'Una explicación directa del problema y la solución.' }, { src: '/gc-vsl-2.png', label: 'Video comercial', caption: 'Una pieza breve para preparar una reunión.' }], examples: [{ title: 'Problema', description: 'Explica un dolor que el cliente ya reconoce.', example: 'Qué revisar antes de que este problema escale.' }, { title: 'Criterio', description: 'Muestra cómo trabaja tu empresa.', example: 'Así evaluamos el problema antes de proponer una solución.' }, { title: 'Caso de uso', description: 'Da contexto a una experiencia real sin inventar resultados.', example: 'Qué hicimos, qué cambió y qué aprendimos.' }] },
  investment: { title: 'Implementación y operación mensual.', introduction: 'El setup deja el sistema listo. La operación mantiene listas, campañas, contenido y aprendizaje.', plans: [{ eyebrow: 'Implementación', title: 'Sistema inicial', price: '$750.000', cadence: 'CLP · pago único', deliverables: ['Workshop de oferta, audiencia y problemas prioritarios', 'Configuración de hasta 3 dominios y sus correos', 'SPF, DKIM, DMARC y calentamiento inicial', 'Criterios de segmentación y primera lista de cuentas', '2 secuencias de 3–5 emails', 'Derivación de respuestas al CRM o agenda', '1 sesión audiovisual de hasta media jornada', '4 videos o clips comerciales editados', 'Dashboard base de entregabilidad y respuestas'] }, { eyebrow: 'Operación mensual', title: 'Campañas activas', price: '$650.000', cadence: 'CLP · mensual', featured: true, deliverables: ['Búsqueda y enriquecimiento de cuentas objetivo', 'Gestión de campañas y salud de correos', 'Pruebas de segmentos, asuntos y mensajes', 'Clasificación y derivación de respuestas', '1 sesión audiovisual mensual', '6–8 piezas editadas para email y canales orgánicos', 'Reporte de entregabilidad, respuestas y reuniones', 'Reunión quincenal de optimización'] }], addons: [{ title: 'Caso de éxito audiovisual', price: '+$250.000', cadence: 'por caso', description: 'Entrevista, edición y versiones breves para secuencias y redes.' }, { title: 'Landing de campaña', price: '+$350.000', cadence: 'pago único', description: 'Página enfocada en una oferta y audiencia específicas.' }], guarantee: 'No se garantiza un número de reuniones. Revisamos entregabilidad, calidad de respuestas, aprendizaje de mercado y oportunidades calificadas.' },
  timeline: { title: 'Así ponemos el sistema en marcha.', items: [{ period: 'Semana 1', title: 'Oferta y audiencia', description: 'Alineamos el mensaje, las empresas objetivo y la llamada a la acción.' }, { period: 'Semana 2', title: 'Configuración', description: 'Preparamos dominios, correos, autenticación y seguimiento.' }, { period: 'Semana 3', title: 'Mensajes y videos', description: 'Creamos secuencias y grabamos las primeras piezas.' }, { period: 'Semana 4', title: 'Lanzamiento', description: 'Activamos envíos graduales y revisamos las primeras respuestas.' }, { period: 'Mes 2+', title: 'Optimización', description: 'Ajustamos audiencias, mensajes y contenido con datos reales.' }] },
  closing: { title: '¿Quieres instalar este sistema en tu empresa?', body: 'Completa el formulario y revisamos si el servicio encaja con tu oferta, mercado y capacidad comercial.', terms: [{ label: 'Setup', value: 'Al iniciar' }, { label: 'Operación', value: 'Mensual' }, { label: 'Software', value: 'A cargo del cliente' }, { label: 'Envío', value: 'Gradual' }, { label: 'Siguiente paso', value: 'Te contactamos' }] },
};
