import type { ProposalData } from '../../lib/proposals/types';

export const marketingAutomationBaseProposal: ProposalData = {
  id: 'base-automatizacion-5d77', mode: 'offer', client: 'Oferta base · Automatización', dateLabel: '2026', eyebrow: 'Auditoría de automatizaciones',
  titleLines: ['Auditoría de', 'automatizaciones'], accentLine: 'de marketing.',
  introduction: 'Revisamos cómo entran los leads, cómo pasan por tu CRM y dónde se pierde tiempo para recomendar qué automatizar primero.',
  quote: 'No es una venta de software. Es una auditoría para ordenar el proceso antes de conectar herramientas.', heroStats: [],
  heroSummary: { title: 'Qué recibes', items: [{ title: 'Mapa del proceso actual', body: 'Vemos cómo entra un lead y qué pasa hasta ventas, agenda o postventa.' }, { title: 'Lista de prioridades', body: 'Ordenamos qué automatizar primero según impacto, esfuerzo y riesgo.' }, { title: 'Plan de implementación', body: 'Definimos datos, disparadores, responsables y herramientas necesarias.' }] },
  sectionLabels: { diagnosis: 'Qué revisamos', solution: 'Qué recibes', timeline: 'Cómo funciona la auditoría', closing: 'Agenda una auditoría' },
  interestOptions: ['Quiero revisar mi CRM y captación de leads', 'Quiero automatizar seguimiento comercial', 'Quiero conectar herramientas que ya uso', 'Quiero conversar primero'],
  diagnosis: { title: 'Encontramos dónde se pierde tiempo y oportunidades.', introduction: 'La auditoría revisa tareas manuales, datos duplicados y momentos donde un lead queda sin responsable o sin próxima acción.', stats: [{ value: '01', label: 'Entrada de leads', context: 'Formularios, anuncios, WhatsApp, email y otros canales de captura.' }, { value: '02', label: 'CRM y seguimiento', context: 'Estados, responsables, tareas y alertas que hoy funcionan de forma manual.' }, { value: '03', label: 'Herramientas conectadas', context: 'Email, agenda, pagos, soporte y plataformas que ya usa tu equipo.' }], conclusion: 'Al terminar sabrás qué automatizar primero, qué no conviene automatizar todavía y qué información necesita el equipo para trabajar mejor.' },
  solution: { title: 'Una auditoría que termina en decisiones claras.', introduction: 'No partimos implementando. Primero entendemos cómo trabaja hoy el equipo y dejamos un plan que se pueda ejecutar por fases.', pillars: [{ title: 'Mapa del recorrido', description: 'Documentamos entradas, estados, responsables y salidas desde el primer contacto.', tag: 'Proceso · Responsables' }, { title: 'Revisión de herramientas', description: 'Miramos CRM, formularios, email, WhatsApp, agenda y las plataformas que ya existen.', tag: 'Stack · Datos' }, { title: 'Prioridades', description: 'Ordenamos oportunidades por impacto comercial, horas ahorradas, complejidad y riesgo.', tag: 'Impacto · Esfuerzo' }, { title: 'Plan técnico', description: 'Definimos flujos, datos, disparadores, excepciones y pasos de implementación.', tag: 'CRM · n8n · APIs' }] },
  timeline: { title: 'Cómo funciona la auditoría.', items: [{ period: 'Sesión 1', title: 'Conocemos el proceso', description: 'Conversamos con marketing, ventas u operaciones para entender cómo se trabaja realmente.' }, { period: 'Días 2–4', title: 'Mapeamos y revisamos', description: 'Documentamos sistemas, entradas, pérdidas de información y tareas repetitivas.' }, { period: 'Sesión 2', title: 'Definimos prioridades', description: 'Revisamos las oportunidades y elegimos qué automatizar primero.' }, { period: 'Entrega', title: 'Recibes el plan', description: 'Te entregamos el mapa, backlog priorizado, dependencias y fases recomendadas.' }] },
  closing: { title: 'Agenda una auditoría de tu operación.', body: 'Completa el formulario. Primero confirmamos si hay un problema automatizable y qué personas de tu equipo deberían participar.', terms: [{ label: 'Primera sesión', value: '45 minutos' }, { label: 'Participantes', value: 'Marketing + ventas' }, { label: 'Entregable', value: 'Plan de acción' }, { label: 'Precio', value: 'Según alcance' }, { label: 'Siguiente paso', value: 'Te contactamos' }] },
};
