import type { ProposalData } from '../../lib/proposals/types';

export const socialMediaBaseProposal: ProposalData = {
  id: 'base-redes-3a91', mode: 'offer', client: 'Oferta base · Redes', dateLabel: '2026', eyebrow: 'Manejo de redes sociales',
  titleLines: ['Manejo de redes', 'sociales y'], accentLine: 'producción mensual.',
  introduction: 'Planificamos, producimos, publicamos y medimos contenido para que tu marca tenga presencia constante en Instagram, TikTok, LinkedIn y los canales donde hoy está tu audiencia.',
  quote: 'Tu equipo recibe un calendario claro, contenido listo para publicar y una revisión mensual de lo que conviene repetir o ajustar.', heroStats: [],
  heroSummary: { title: 'Qué incluye el servicio', items: [{ title: 'Estrategia mensual', body: 'Calendario, temas y formatos conectados con los objetivos de la marca.' }, { title: 'Producción y diseño', body: 'Reels, posts y stories adaptados a cada canal y a tu material disponible.' }, { title: 'Publicación y seguimiento', body: 'Copies, programación y revisión de resultados para mejorar el próximo mes.' }] },
  sectionLabels: { diagnosis: 'Qué hacemos', solution: 'Cómo trabajamos', investment: 'Planes mensuales', timeline: 'Cómo es trabajar con nosotros', closing: '¿Te interesa este servicio?' },
  interestOptions: ['4 reels, 4 posts y 10 stories · $300.000 CLP/mes', '8 reels, 6 posts y 15 stories · $600.000 CLP/mes', '12 reels, 10 posts y 20 stories · $1.000.000 CLP/mes', 'No sé cuál plan necesito'],
  diagnosis: { title: 'Un equipo para manejar tus redes cada mes.', introduction: 'No tienes que coordinar por separado estrategia, grabación, diseño y publicación. Nos hacemos cargo del ciclo completo según el plan que elijas.', stats: [{ value: '01', label: 'Estrategia', context: 'Definimos foco, calendario y piezas antes de empezar a producir.' }, { value: '02', label: 'Producción', context: 'Grabamos, editamos y diseñamos el contenido mensual.' }, { value: '03', label: 'Publicación y seguimiento', context: 'Preparamos copies, programamos y revisamos qué funcionó.' }], conclusion: 'El resultado es una cuenta activa y ordenada, con contenido que se puede medir y mejorar mes a mes.' },
  solution: { title: 'Qué incluye el trabajo mensual.', introduction: 'El plan define el volumen de contenido, las jornadas de producción y el nivel de operación que asumimos.', pillars: [{ title: 'Planificación', description: 'Acordamos los temas, formatos y fechas de publicación del mes.', tag: 'Calendario · Mensajes' }, { title: 'Grabación y edición', description: 'Convertimos una sesión o tu material en reels, posts y stories listos para usar.', tag: 'Video · Diseño' }, { title: 'Publicación', description: 'Escribimos copies y programamos las piezas en los canales definidos.', tag: 'Instagram · TikTok · LinkedIn' }, { title: 'Revisión mensual', description: 'Miramos alcance, interacción, preguntas y formatos para tomar mejores decisiones.', tag: 'Reporte · Ajustes' }] },
  investment: { title: 'Elige el volumen de contenido que necesitas.', introduction: 'Los precios son mensuales. Se ajustan si hay más canales, locaciones o requerimientos especiales de producción.', plans: [
    { eyebrow: 'Opción 01', title: '4 reels · 4 posts · 10 stories', price: '$300.000', cadence: 'CLP · mensual', deliverables: ['4 reels editados desde material entregado por el cliente', '4 posts estáticos o carruseles', '10 stories adaptadas del contenido mensual', 'Calendario editorial y copies', 'Programación en 1 plataforma principal', 'Reporte mensual breve', '1 ronda consolidada de ajustes'] },
    { eyebrow: 'Opción 02', title: '8 reels · 6 posts · 15 stories', price: '$600.000', cadence: 'CLP · mensual', featured: true, deliverables: ['8 reels editados', '6 posts estáticos o carruseles', '15 stories', '1 sesión de producción de hasta media jornada en Santiago', 'Dirección, pauta de grabación y calendario editorial', 'Copies y programación en hasta 2 plataformas', 'Moderación básica de comentarios', 'Reporte y reunión mensual de aprendizaje'] },
    { eyebrow: 'Opción 03', title: '12 reels · 10 posts · 20 stories', price: '$1.000.000', cadence: 'CLP · mensual', deliverables: ['12 reels editados', '10 posts estáticos o carruseles', '20 stories', 'Hasta 2 medias jornadas de producción en Santiago', 'Estrategia, copies y publicación en hasta 3 plataformas', 'SAC básico en horario hábil con protocolo aprobado', 'Bot para preguntas frecuentes y calificación inicial de DMs', 'Automatización de derivación a WhatsApp, agenda o CRM', 'Dashboard y reunión mensual de optimización'] }
  ], addons: [{ title: 'Media jornada adicional', price: '+$180.000', cadence: 'por sesión', description: 'Producción adicional dentro de Santiago con pauta acordada previamente.' }, { title: 'Paid media', price: 'A cotizar', cadence: 'sin inversión publicitaria', description: 'Gestión de campañas y adaptación de creatividades según objetivo, canal y presupuesto.' }] },
  timeline: { title: 'Cómo es trabajar con nosotros cada mes.', items: [{ period: 'Semana 1', title: 'Inicio y calendario', description: 'Definimos los temas, formatos, responsables y fechas del mes.' }, { period: 'Semana 2', title: 'Producción', description: 'Grabamos o recibimos material, editamos y diseñamos las piezas.' }, { period: 'Semana 3', title: 'Aprobación y publicación', description: 'Revisamos, ajustamos y dejamos el contenido programado.' }, { period: 'Semana 4', title: 'Resultados y mejora', description: 'Revisamos señales reales para decidir qué mantener y qué cambiar.' }] },
  closing: { title: '¿Quieres que manejemos tus redes?', body: 'Completa el formulario y te recomendaremos un plan según tu marca, canales y material disponible.', terms: [{ label: 'Servicio', value: 'Mensual' }, { label: 'Canales', value: 'Según plan' }, { label: 'Producción', value: 'Según plan' }, { label: 'Pauta', value: 'No incluida' }, { label: 'Siguiente paso', value: 'Te contactamos' }] },
};
